# Generated by Django 3.2.9 on 2021-11-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211119_1325'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_order', to='orders.Order', verbose_name='Заказы покупателя'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
